---
# tasks file for anti-virus
- name: Place ClamAV gpg key
  ansible.builtin.copy:
    src: talos.gpg.txt
    dest: /etc/pki/rpm-gpg/talos.gpg.txt

- name: Import ClamAV gpg key
  ansible.builtin.rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/talos.gpg.txt

- name: ClamAV package installation
  ansible.builtin.dnf:
    name: "https://www.clamav.net/downloads/production/clamav-1.3.1.linux.x86_64.rpm"
    state: present
    disable_gpg_check: true

- name: Create clamav service "group" account
  ansible.builtin.group:
    name: clamav
    system: true
    state: present

- name: Create clamav service "user" account
  ansible.builtin.user:
    name: clamav
    system: true
    shell: /bin/false
    group: clamav
    state: present
    create_home: false
    comment: "Clam Antivirus"

- name: Set ownership of clamav directory to clamav service account
  ansible.builtin.file:
    path: "/usr/local/share/clamav"
    state: directory
    recurse: yes
    owner: clamav
    group: clamav

- name: Generate clamconf for mail filter
  ansible.builtin.shell:
    cmd: "/usr/local/bin/clamconf -g clamav-milter.conf > /usr/local/etc/clamav-milter.conf.sample"

- name: Copy example clamav configs
  ansible.builtin.copy:
    src: "/usr/local/etc/{{ item }}.conf.sample"
    dest: "/usr/local/etc/{{ item }}.conf" 
    remote_src: true
  with_items:
    - "clamd" 
    - "freshclam"
    - "clamav-milter"

- name: Remove Example declaration from clam* file
  ansible.builtin.lineinfile:
    path: "/usr/local/etc/{{ item }}.conf" 
    state: absent
    regexp: '^Example'
  with_items:
    - "clamd" 
    - "freshclam"
    - "clamav-milter"

- name: Set User declaration from clam* file
  ansible.builtin.lineinfile:
    path: "/usr/local/etc/{{ item }}.conf" 
    state: present
    regexp: '^#User '
    line: 'User clamav'
  with_items:
    - "clamd" 

- name: Set ownership of freshclam log file to clamav service account
  ansible.builtin.file:
    path: "/var/log/freshclam.log"
    state: touch
    mode: '0600'
    owner: clamav
    group: clamav

- name: Generate a job that runs freshclam hourly.
  ansible.builtin.cron:
    name: "FreshClamz"
    minute: "22"
    hour: "*"
    user: clamav
    job: "/usr/local/bin/freshclam --quiet"

- name: Selinux Modification for clamav
  ansible.posix.seboolean:
    name: antivirus_can_scan_system
    state: true
    persistent: true