---
# tasks file for tomcat
- name: Tomcat package installation
  ansible.builtin.dnf:
    name: tomcat
    state: present

- name: Tomcat start and enable
  ansible.builtin.systemd:
    name: tomcat
    state: started
    enabled: true


