---

- name: Run Cat 3 STIG 2xxxxx tasks
  ansible.builtin.import_tasks:
    file: RHEL-09-2xxxxx.yml

- name: Run Cat 3 STIG 4xxxxx tasks
  ansible.builtin.import_tasks:
    file: RHEL-09-4xxxxx.yml

- name: Run Cat 3 STIG 6xxxxx tasks
  ansible.builtin.import_tasks:
    file: RHEL-09-6xxxxx.yml
